/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package jbitset

import org.junit.Assert
import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test
    fun testBasicBitBuffer() {
        val bb1 = BitBuffer()
        bb1[0] = true
        bb1[42] = true

        val bb2 = BitBuffer()
        bb2[0] = true
        bb2[42] = true
        println(bb1 == bb2)
        println(bb1.isSuperSetOf(bb2))
        println(bb2.isSuperSetOf(bb1))
        println(bb2.isSubSetOf(bb1))
        val bbu = bb1.union(bb2)
        println(bb1 == bbu)
        val bbi = bb1.intersection(bb2)
        println(bb2 == bbi)

        bb1[0] = false
        println(bb1.isSubSetOf(bb2))
    }

    @Test
    fun testBasicSparseBitBuffer(){
        val sb1 = SparseBitSet()
        val sb2 = SparseBitSet()
        Assert.assertEquals(sb1, sb2 )
    }
}
